//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eli
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewFinanceFactorDebator
    {
        public int FinancingFactorNumber { get; set; }
        public string FinancingFactorName { get; set; }
        public string FinancingFactorType { get; set; }
        public string FinancingFactorAddress { get; set; }
        public string FinancingFactorContactName { get; set; }
        public string FinancingFactorContcatPhoneNumber { get; set; }
        public string FinancingFactorContactMail { get; set; }
        public Nullable<System.DateTime> TreatmentDate { get; set; }
        public Nullable<System.TimeSpan> TreatmentStartTime { get; set; }
        public string ID { get; set; }
        public string PatientName { get; set; }
        public string TherapistName { get; set; }
    }
}
